name: rich_editor
description: WYSIWYG editor for Flutter with a rich set of supported formatting options.
version: 0.1.0
homepage: https://github.com/JideGuru/rich_editor

environment:
  sdk: ">=2.19.6 <4.0.0"
  flutter: ">=2.11.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^5.7.2+3
  mime: ^1.0.4
  flutter_widget_from_html_core: ^0.10.5
  flutter_colorpicker: ^1.0.3
  path: ^1.8.3
  xml2json: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/editor/
